APPQ-3594 Build Anki using turboscript
turboapps/turbome pull request #96
Opened 2023-07-12 23:00 UTC by huiyu-turbo

Added a TurboScript for Anki (https://apps.ankiweb.net/)

2023-07-12 23:08 UTC, johnsu requested changes
I ran `turbo build https://raw.githubusercontent.com/turboapps/turbome/ec06748168effff767590467f98745afb8523c85/anki/turbo.me` but failed with setup.exe not found.

```
>turbo build https://raw.githubusercontent.com/turboapps/turbome/ec06748168effff767590467f98745afb8523c85/anki/turbo.me
Using VM 23.6.18 from local
Step 0: meta title="Anki"
Step 1: meta namespace="anki"
Step 2: meta name="anki"
Step 3: using gnu/wget microsoft/powershell
Using image clean:40 from local
Using image wget:1.11.4 from local
Downloading image powershell:5 from https://hub.turbo.net/users/microsoft
Step 4: cmd (mkdir, @SYSDRIVE@\Workspace)

Step 5: workdir @SYSDRIVE@\Workspace
Step 6: batch
        cmd ("echo $webpage = Invoke-WebRequest -Uri "https://apps.ankiweb.net/downloads/archive/" >> GetVersion.ps1")
        cmd ("echo $releases = $webpage.Links.href ^| where {$_ -like "*windows-qt6.exe"} ^| sort >> GetVersion.ps1")
        cmd (echo $latest = $releases[-1] >> GetVersion.ps1)
        cmd ("echo $version = [regex]::Match($latest, "\d+\.\d+\.\d+").Value >> GetVersion.ps1")
        cmd (echo $version >> GetVersion.ps1)

Step 7: cmd ("powershell -executionpolicy remotesigned -File "GetVersion.ps1"")

2.1.65
Step 8: cmd (echo, https://github.com/ankitects/anki/releases/download/2.1.65/anki-2.1.65-windows-qt6.exe)

https://github.com/ankitects/anki/releases/download/2.1.65/anki-2.1.65-windows-qt6.exe
Step 9: cmd (wget, --no-check-certificate, --no-verbose, -O, Setup.exe, %url%)

SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = c:/progra~1/wget/etc/wgetrc
Step 10: cmd (Setup.exe, /S, /D=c:\Anki)

Step 11: cmd (del, Setup.exe, /Q)

Could Not Find C:\Workspace\Setup.exe
```

2023-07-13 00:06 UTC, michaelrush requested changes

2023-07-13 00:06 UTC, michaelrush commented on anki/turbo.me
> +using gnu/wget, microsoft/powershell
lets remove the microsoft/powershell image here to keep the build script minimal. This should also fix the build error John and I were seeing on our boxes.

2023-07-13 00:11 UTC, huiyu-turbo commented on anki/turbo.me
> +using gnu/wget, microsoft/powershell
I removed it and the script can run without PowerShell dependency.

2023-07-13 00:40 UTC, michaelrush commented
The build now completes and the application launches but the main window does not render any content. I tried importing a deck from anki.com (File > Import) and studying it (Tools > Study Deck) but nothing appeared.
![image](https://github.com/turboapps/turbome/assets/1094001/1231efaf-5d21-4103-af37-d94a7f00394b)

I opened with Studio and enabled Chromium Virtualization and now it works:
![image](https://github.com/turboapps/turbome/assets/1094001/313bc51f-6d3f-43ee-8d18-e52a3cb2c106)

However I'm not aware of a way to do through through TurboScript. I do see a way to do it through PowerShell though:

2023-07-13 17:59 UTC, huiyu-turbo commented
Added `enable ChromiumSupport`. It should work now.

2023-07-13 18:06 UTC, michaelrush approved these changes

2023-07-13 18:07 UTC, merged